services:
  - type: web
    name: heroesData
    env: node
    region: Frankfurt
    buildCommand: cd heroesData && npm install
    startCommand: cd heroesData && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        value: your-session-secret
      - key: JWT_SECRET
        value: your-jwt-secret